//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItem
    {
        public System.Guid PurchaseItemId { get; set; }
        public Nullable<System.Guid> PurchaseId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Tax { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
